#!/usr/bin/env python3
"""Emit the bot-rename migration + rollback from bot_roster_updated.tsv.

Reads the 7-column roster (id, name, level, vocation, vocation_id, town_id, new_name)
and writes two SQL files:

    database/bots/19_bot_rename.sql           old name -> new name
    database/bots/19_bot_rename_rollback.sql  new name -> old name

Design notes (see implementation_plans/BOT_RENAME_997.md):

* Every UPDATE is guarded on id AND the expected current name AND account_id. That makes
  the script idempotent (a second run matches nothing) and drift-safe (a bot renamed by
  other means is skipped rather than clobbered).
* Wrapped in a transaction so a mid-file failure leaves zero partial renames.
* Rows whose new_name contains a digit are SKIPPED by decision: those names are
  de-duplication artifacts (`Giles2`, `Jonah3`), and those bots keep their original name.
* `players.name` carries a UNIQUE index. Statement order is only safe because the new-name
  set and the retained-name set are provably disjoint -- asserted below, not assumed.

Run from the repo root:  python tools/bot_population_generator/generate_rename_sql.py
"""

import csv
import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROSTER = REPO / "tools" / "bot_population_generator" / "bot_roster_updated.tsv"
OUT_FWD = REPO / "database" / "bots" / "19_bot_rename.sql"
OUT_REV = REPO / "database" / "bots" / "19_bot_rename_rollback.sql"

BOT_ACCOUNT_ID = 65000

# The 14 real (non-bot) characters. A new bot name colliding with one of these would be
# rejected by the UNIQUE index mid-transaction and roll the whole migration back.
REAL_PLAYERS = [
    "Rookstayer", "Mago Pipi", "Powerhealz", "Legolas", "The Hulk", "GOD", "ADMIN",
    "Godd", "Rook Sample", "Sorcerer Sample", "Druid Sample", "Paladin Sample",
    "Knight Sample", "Monk Sample",
]


def sql_str(value: str) -> str:
    """Single-quote a name for MySQL. Rejects anything needing more than quote-doubling."""
    if re.search(r"[\\`;\x00-\x1f]", value):
        raise ValueError(f"unsafe character in name: {value!r}")
    return "'" + value.replace("'", "''") + "'"


def main() -> int:
    rows = list(csv.DictReader(ROSTER.open(encoding="utf-8"), delimiter="\t"))

    renames, kept = [], []
    for r in rows:
        old, new = r["name"].strip(), r["new_name"].strip()
        (kept if re.search(r"\d", new) else renames).append((int(r["id"]), old, new))

    # ---- assertions: fail loudly rather than emit a migration that corrupts the DB ----
    final_names = [n for _, _, n in renames] + [o for _, o, _ in kept]
    dupes = [n for n, c in Counter(x.lower() for x in final_names).items() if c > 1]
    assert not dupes, f"duplicate names in post-migration set: {dupes}"

    real_lower = {p.lower() for p in REAL_PLAYERS}
    clash = [n for n in final_names if n.lower() in real_lower]
    assert not clash, f"new name collides with a real player: {clash}"

    new_lower = {n.lower() for _, _, n in renames}
    retained_lower = {o.lower() for _, o, _ in kept}
    overlap = new_lower & retained_lower
    assert not overlap, f"new name collides with a retained old name: {overlap}"

    assert len(rows) == 997, f"expected 997 roster rows, got {len(rows)}"
    assert len({i for i, _, _ in renames + kept}) == 997, "duplicate ids in roster"

    header = (
        "-- Bot rename: {n} of 997 bots renamed from bot_roster_updated.tsv.\n"
        "-- {k} bots deliberately KEEP their original name (new_name contained a digit,\n"
        "-- a de-duplication artifact). See implementation_plans/BOT_RENAME_997.md.\n"
        "--\n"
        "-- MUST be applied with canary STOPPED: iologindata_save_player.cpp rewrites\n"
        "-- players.name on every save, so a live apply is silently reverted.\n"
        "--\n"
        "-- Idempotent: each UPDATE is guarded on id + expected current name + account_id.\n"
        "-- Generated by tools/bot_population_generator/generate_rename_sql.py -- do not hand-edit.\n\n"
        "START TRANSACTION;\n\n"
    )

    def emit(path: Path, pairs, reverse: bool) -> None:
        with path.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(header.format(n=len(renames), k=len(kept)))
            if reverse:
                fh.write("-- ROLLBACK direction: new name -> original name.\n\n")
            for pid, old, new in pairs:
                frm, to = (new, old) if reverse else (old, new)
                fh.write(
                    f"UPDATE `players` SET `name` = {sql_str(to)} "
                    f"WHERE `id` = {pid} AND `name` = {sql_str(frm)} "
                    f"AND `account_id` = {BOT_ACCOUNT_ID};\n"
                )
            fh.write("\nCOMMIT;\n")

    OUT_FWD.parent.mkdir(parents=True, exist_ok=True)
    emit(OUT_FWD, renames, reverse=False)
    emit(OUT_REV, renames, reverse=True)

    print(f"renamed : {len(renames)}")
    print(f"kept    : {len(kept)} (digit in new_name)")
    for pid, old, new in kept:
        print(f"          {pid}  {old:<24} (proposed {new})")
    print(f"\nwrote {OUT_FWD.relative_to(REPO)}")
    print(f"wrote {OUT_REV.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
